apiVersion: v1
kind: Service
metadata:
  name: banking-system-api
spec:
  selector:
    app: banking-system-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
