apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-system-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-system-api
  template:
    metadata:
      labels:
        app: banking-system-api
    spec:
      containers:
      - name: api
        image: arushpatel/banking-system-client
        ports:
        - containerPort: 5001
