apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-system-server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: banking-system-server
  template:
    metadata:
      labels:
        app: banking-system-server
    spec:
      containers:
      - name: server
        image: arushpatel/banking-system-server
        ports:
        - containerPort: 5000
        args: ["python", "Server.py", "input.json"]
