apiVersion: v1
kind: Service
metadata:
  name: banking-system-server
spec:
  selector:
    app: banking-system-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
